version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: ./wardrobe_organizer/
    volumes:
      - static:/app/static/
      - media:/app/media/
    env_file: .env
    depends_on:
      - db

  gateway:
    build: ./gateway/
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - web
