# Generated by Django 3.2.16 on 2023-05-22 12:50

from django.db import migrations, models
import wardrobe.models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=wardrobe.models.user_directory_path, verbose_name='Изображение'),
        ),
    ]
