# Generated by Django 3.2.16 on 2023-05-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_alter_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='using_information',
        ),
        migrations.RemoveField(
            model_name='use',
            name='user',
        ),
        migrations.AddField(
            model_name='use',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use', to='wardrobe.item', unique_for_date=True, verbose_name='Предмет'),
        ),
    ]
