# Generated by Django 3.2.16 on 2023-05-26 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_auto_20230527_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='use',
            options={'default_related_name': 'use', 'ordering': ['-date'], 'verbose_name': 'Информация об использовании', 'verbose_name_plural': 'Информация об использовании'},
        ),
        migrations.RemoveField(
            model_name='use',
            name='time',
        ),
        migrations.AddField(
            model_name='use',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата использования'),
        ),
        migrations.AlterField(
            model_name='use',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use', to='wardrobe.outfit', verbose_name='Предмет'),
        ),
        migrations.AddConstraint(
            model_name='use',
            constraint=models.UniqueConstraint(fields=('outfit', 'date'), name='unique_date_use'),
        ),
    ]
