# Generated by Django 3.2.16 on 2023-05-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0006_auto_20230527_0026'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='use',
            name='unique_date_use',
        ),
    ]
