# Generated by Django 3.2.16 on 2023-05-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0007_remove_use_unique_date_use'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='use',
            constraint=models.UniqueConstraint(fields=('outfit', 'date'), name='unique_date_use'),
        ),
    ]
