# Generated by Django 3.2.16 on 2025-03-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0008_use_unique_date_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='category',
            field=models.CharField(choices=[('Top', 'Верх'), ('Bottom', 'Низ'), ('Full length', 'Полная длина'), ('Outerwear', 'Верхняя одежда'), ('Shoes', 'Обувь'), ('Accessories', 'Аксессуары'), ('Other', 'Другое')], max_length=256, verbose_name='Категория'),
        ),
    ]
